### ISSUE TITLE
same problem as last patch

### ISSUE THREAD

**Issue by kesirov** [matortheeternal/zedit#126]
the same problem happend to me that u said u fixed, in the last patch

**Comment by matortheeternal** [comment]
What problem are you referring to?

**Comment by kesirov** [comment]
this one
![Unbenannt6](https://user-images.githubusercontent.com/50520494/57583842-05763600-74d5-11e9-98a1-2824e90c4336.PNG)

**Comment by matortheeternal** [comment]
What parameters are you starting zEdit with?  Try removing them.

**Comment by kesirov** [comment]
im running it through vortex overall, i tried it without still the same problem after trying to run another game with it catches the game but the same problem apperas after the second start

**Comment by matortheeternal** [comment]
I don't really have enough information as it stands to assess the problem.  You claim this is the same as the problem mentioned in the changelog, but that issue only occurs when you provide a `-profile` argument when starting the application.  If you aren't providing that then your problem is different and you should provide a screenshot of the error message.

**Comment by kesirov** [comment]
here is a screenshot 
sorry for not doing it ....
![Unbenannt9](https://user-images.githubusercontent.com/50520494/57732653-db23a480-769d-11e9-976f-b8bf2304b59b.PNG)

**Comment by kesirov** [comment]
nevermind i found the problem was just a brain lag im sorry ...
