### ISSUE TITLE
NMM load order out of order (sometimes)

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/zedit#21]
Some versions of NMM use the `plugin.esp=1` format for `plugins.txt`.  XEditLib wasn't parsing this format correctly.  Until the next release of zEdit you can grab this [hotfix release](http://puu.sh/xA6fD.zip) of XEditLib.dll, which should fix the problem.

**Comment by derossm** [comment]
Seems to just invert the selection; all the dlc (which are no longer listed in Plugins.txt for SSE/F4 by design) and the single plugin I have unchecked are all checked now. The order is still the same (incorrect) as with the old XEditLib.dll from alpha v0.1.1+hotfix portable.

Side note- it would be nice if ZEdit portable remembered which game was last selected when opening it. Both as the new default in the drop-down, and an option to skip the selection screen next time.

**Comment by matortheeternal** [comment]
> The order is still the same (incorrect)

Yeah, I found out as much from another user, didn't update this issue though.  The `=` format seems to be a bit of a pain to parse properly.  I'll get it working eventually.

> Side note- it would be nice if ZEdit portable remembered which game was last selected when opening it. Both as the new default in the drop-down, and an option to skip the selection screen next time.

It's supposed to.  I'm aware that it's not currently and I'll be fixing it (hopefully) for the next release.

**Comment by matortheeternal** [comment]
It seems this has finally been fixed with the latest XEditLib.dll.  It turns out that NMM wasn't actually using the Plugin.esp=1 format, users were sending me their load order exported from the NMM GUI, which uses this format, but the actual `plugins.txt` file uses the asterisk format that was introduced by Fallout 4 and SSE.   This simple mistake caused me to waste many hours creating parsing code for the Plugins.esp=1 format and being utterly confused why it wasn't working.  Ultimately it turned out that it was just a simple issue in the conditional for when the load order should be sorted by plugin dates.
