### ISSUE TITLE
zEdit Patcher not working

### ISSUE THREAD

**Issue by goxaxa** [matortheeternal/zedit#40]
I have zEdit installed, and can call it from Mod Organiser, and can look at Skyrim .esp files - this is all working OK.

But when I right-click, select "Manage Patchers" and click "Build" - sometimes nothing happens, other times zEdit freezes and stops responding.

I have all the patchers listed on zedit-unified-patching-framework github page installed. I tried them all, and they all fail the same way.

I looked in the zEdit directory to see if there were any logs, and found modorganiser.log which has this:

INFO (11:49:57.0309): Windows Exception (c0000005). Origin: "C:\Windows\SysWOW64\ntdll.dll" (76f0e081). Last hooked call: void *__stdcall CreateFileW_rep(const wchar_t *,unsigned long,unsigned long,struct _SECURITY_ATTRIBUTES *,unsigned long,unsigned long,void *)

**Comment by matortheeternal** [comment]
There are a few possible reasons why this could be happening, zEdit not having filesystem write access is one of them.

If you're interested we can work through the issue on the [Modding Tools Discord](https://discord.gg/GUfRdpT) in real time, else we can go over possible fixes here.  Before we go into any fixes, you can view the zEdit log by pressing Ctrl+Shift+I and going to the console tab.  Any messages in red are errors (post a screenshot or copy-paste the log here).

Windows 10 is most often associated with filesystem issues.  Look into the following:

1. Windows Defender/Other AVs.  Some AVs can interfere with the operation of applications silently from the background.  If you run an AV you can attempt to disable it/add zEdit as an exception to see if that resolves the issue.
2. File ownership/run as admin.  MO should start any application started through it with admin privileges, but this will only work if MO was started with admin privileges.  In addition, sometimes Windows 10 will take ownership of files or folders away from the main admin user, causing issues when other programs attempt to read/write to those files/folders.  You can take ownership of files from the command line.

**Comment by goxaxa** [comment]
Thanks for the offer to use Discord, but I'd prefer to go over the fixes here.

This is the console tab output:
There were no red error messages.
-----------------------------------------------------------------------------------------------------
app.js:27 App directory: C:\Users\user\AppData\Local\Programs\zEdit\0.3.0\resources\app.asar
app.js:7797 Setting game mode to: 3
app.js:9757 Load Order:
Skyrim.esm,Update.esm,Dawnguard.esm,HearthFires.esm,Dragonborn.esm,Unofficial Skyrim Legendary Edition Patch.esp,HighResTexturePack01.esp,HighResTexturePack02.esp,HighResTexturePack03.esp
app.js:9758 Active Plugins:
Skyrim.esm,Update.esm,Dawnguard.esm,HearthFires.esm,Dragonborn.esm,Unofficial Skyrim Legendary Edition Patch.esp
app.js:9040 Loading:
Skyrim.esm,Update.esm,Dawnguard.esm,HearthFires.esm,Dragonborn.esm,Unofficial Skyrim Legendary Edition Patch.esp
app.js:7789 ProgramPath=C:\Users\user\AppData\Local\Programs\zEdit\0.3.0\
Version=0.2.1.2
GameName=Skyrim
AppName=TES5
LongGameName=Skyrim
DataPath=c:\games\steam\steamapps\common\Skyrim\data\
AppDataPath=C:\Users\user\AppData\Local\Skyrim\
MyGamesPath=C:\Users\user\Documents\My Games\Skyrim\
GameIniPath=C:\Users\user\Documents\My Games\Skyrim\Skyrim.ini

app.js:2099 Loading Skyrim.esm (1/6)
Loading Update.esm (2/6)
Loading Dawnguard.esm (3/6)
Loading HearthFires.esm (4/6)
Loading Dragonborn.esm (5/6)
Loading Unofficial Skyrim Legendary Edition Patch.esp (6/6)
Loading resources from Skyrim - Misc.bsa
Loading resources from Skyrim - Shaders.bsa
Loading resources from Skyrim - Textures.bsa
Loading resources from Skyrim - Interface.bsa
Loading resources from Skyrim - Animations.bsa
Loading resources from Skyrim - Meshes.bsa
Loading resources from Skyrim - Sounds.bsa
Loading resources from Skyrim - Voices.bsa
Loading resources from Skyrim - VoicesExtra.bsa
Loading resources from Update.bsa
Loading resources from Dawnguard.bsa
Loading resources from HearthFires.bsa
Loading resources from Dragonborn.bsa
Loading resources from Unofficial Skyrim Legendary Edition Patch.bsa
Done loading files.
-----------------------------------------------------------------------------------------------------

I use Windows 7, not Windows 10.
I disabled my AV programs, but the zEdit patcher still did not work.

My Skyrim setup follows the STEP guide.
I installed Steam and Mod Organiser to C:/Games/ which I have write access to, and not to a system protected directory like C:/Program Files/.
I run from a standard user (non-admin) account and run Mod Organiser as a standard user, and it works fine for MO, LOOT, Wrye Bash, Mator Smash, Mator Merge Plugins, Mator zEdit (without the patcher)

When I click on "Build" for the zEdit patcher, the console tab shows nothing new.

**Comment by matortheeternal** [comment]
OK, thanks for the additional information.  I'll do some research on my end to see if I can recreate your issue.

**Comment by matortheeternal** [comment]
I downloaded the latest portable release of zEdit from GitHub (Alpha Release v0.3), extracted it to my secondary hard drive: `E:\Program Files (x86)\zEdit`, then manually installed the latest example patcher from GitHub source code.

To manually install the patcher module I:

1. Downloaded the source code ZIP from GitHub
2. Extracted the `dist` folder to zEdit's `modules` folder.
3. Renamed the `dist` folder to the `id` specified in the patcher's `module.json` file.  (in this case, `matorsExamplePatcher`.

I then started zEdit and noted the patcher listed in the Manage Extensions Modal:

![](http://puu.sh/ztuFR.png)

I then started a Skyrim session and the patch built successfully:

![](http://puu.sh/ztuIo.png)

**Comment by matortheeternal** [comment]
Installing modules from the manage extensions modal appears to be bugged currently, it will be fixed in the near future.

**Comment by goxaxa** [comment]
I followed what you did:
- downloaded the latest portable release of zEdit from GitHub (Alpha Release v0.3)
- manually installed the latest example patcher from GitHub source code
- started zEdit and noted the patches listed in the Manage Extensions Modal
I can see Example Patcher 1.2.1 and Unified Patching Framework 0.6.0 installed.

I start a Skyrim session, select Manage Patchers, tick the Example Patcher, and click Build. The dialog window disappears and nothing else happens, and the patch is not built successfully.
The zEdit application stops responding and I have to start Task Manager and kill it.

**Comment by matortheeternal** [comment]
OK, I'm not sure what's happening for you, but it seems like it must be an issue relating to your system.  I'll do some more research tomorrow.

**Comment by goxaxa** [comment]
I followed the procedure I listed in my last message, but this time for zEdit 0.2.0.
It pops up an error message "TypeError: helpers.newRecord is not a function", but the patcher runs and produces examplePatch.esp with a list of Armor records.

So it looks like the zEdit 0.2.0 patcher works OK, but the zEdit 0.3.0 patcher has a problem, at least for my system.

**Comment by matortheeternal** [comment]
> "TypeError: helpers.newRecord is not a function"

That's just because the example patcher was updated to use `helpers.newRecord` for UPF v0.6.0.  If I give you an older version of the example patcher this error won't occur.

That said, for v0.2.0 to work and v0.3.0 to completely fail is very odd.  I don't think anything fundamental changed, but I'll have to do some more digging into commit histories to evaluate why this might happen.

**Comment by matortheeternal** [comment]
The only reason I can think of for v0.3.0 to fail where v0.2.0 works is an antivirus interfering with the execution for v0.3.0 but not v0.2.0.  I'm going to need more information to act on this.  Can you take a screenshot of exactly what happens with the application when you attempt to run a patcher with v0.3.0?  You've said it freezes, but the way it freezes is important.  Does it create the modal window, or not?  Does the debugger detach?  Does the application turn into a flat white background?  Is it using CPU resources or not?

A screenshot would be good, a video would be even better.  Without any debug information combined with me being unable to recreate the issue there's really nothing I can do.  You should triple check that windows defender isn't running and interfering with the program, and make sure that there isn't any other process on your system that might be messing things up.

**Comment by goxaxa** [comment]
I turned off my AV/security apps and recorded video of zEdit. This platform does not accept video uploads. I tried adding the videos to a zip file, but that was not accepted either.

The Videos.zip file is here
http://www103.zippyshare.com/v/paTYpc8v/file.html

zEdit 0.2.0 seems to work OK - at least it produces an .esp file. But I don't see the "1 patch plugins built successfully" window that you showed in your message above.

zEdit 0.3.0 looks like it gets stuck in an endless loop. Task Manager shows it is still using the CPU, but it completely stops responding and I have to kill it.
One time I left zEdit 0.3.0 running 5-10 mins and it did display a message "1 patch plugin built successfully" but it did not refresh the window properly - the zEdit GUI was not responding.

**Comment by matortheeternal** [comment]
Alright, this helps a lot for me to understand and troubleshoot the problem, thank you.  I'll try to get around to creating and sending you a developer build tomorrow once I've identified what could be causing the problem.

**Comment by matortheeternal** [comment]
Watching the videos, two things leap out at me:

1. You have Windows Aero disabled.  I know OBS sometimes does this automatically, do you run with Windows Aero disabled all the time or only when using OBS?  This might actually be important because...

2. The progress window is never displayed.  When zEdit is performing a large task it creates a progress window which displays either a modal with a progress bar (e.g. in the case of running patchers) or a spinner (e.g. in the case of running a script).  [This is a video](https://puu.sh/zvbU1.mp4) of what running the example patcher looks like on my system with v0.3.0.

The way running a patcher works is it creates a new window with transparency, positions this window above the main application window as a modal (disabling input on the main application window), executes the patcher(s), and then allows the user to close the modal manually once the patching is completed.  In your case this window is never getting displayed.  The patchers runs *and* completes successfully, but you can't see it and you can't interact with the application anymore because the window was never shown on your machine for some reason.  Windows Aero being disabled is a potential culprit.

**Comment by goxaxa** [comment]
I changed the Windows theme years ago, and had completely forgotten about it. I had read
somewhere that Aero just gives you flashy desktop graphics effects that you don't really need, so I changed to the "Windows 7 Basic" theme.

I've not noticed any problems with any other applications before from not using Aero.
Windows 8 and 10 have Metro not Aero (also Linux and MacOS don't have Aero), so how does
zEdit and electron work on those operating systems?

Here are some updated videos, after changing to the "Windows 7" Aero theme.
http://www60.zippyshare.com/v/tjVuc39U/file.html

zEdit 0.2.0
It now displays the progress window, and runs OK.

zEdit 0.3.0
It now displays the progress window, but it stops responding, and I still have to kill it
using Windows Task Manager.

**Comment by matortheeternal** [comment]
> I had read somewhere that Aero just gives you flashy desktop graphics effects that you don't really need

That would generally be true, but without Aero applications cannot create windows with transparency.  Maybe transparency is a "flashy effect", but it's worth noting that any application window which is created with the "transparent" flag is not displays by Windows *at all* if Aero is disabled.

>  I've not noticed any problems with any other applications before from not using Aero.

I imagine most applications check if Aero is running and then create a non-transparent window if it isn't.  That's what I'm going to have to do for zEdit.

> Windows 8 and 10 have Metro not Aero (also Linux and MacOS don't have Aero), so how does
zEdit and electron work on those operating systems?

Metro and Aero serve the same function.  Linux and MacOS have their own native ways of handling transparency, per [the link I shared in my previous comment](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations).

> It now displays the progress window, but it stops responding, and I still have to kill it
using Windows Task Manager.

No it actually worked perfectly, you were just clicking the wrong X.  To close the modal you need to click the X in its upper right corner, however it seems like FontAwesome icons didn't load in the progress window so that icon appears as a square for you.

![](http://puu.sh/zwydU.jpg)
