### ISSUE TITLE
Certain links on "xEdit Comparison" in page of the documentation go nowhere

### ISSUE THREAD

**Issue by RoboticWater** [matortheeternal/zedit#72]
Some of the links in question:
[Advanced Search Modal](https://z-edit.github.io/#/docs?t=Modal%20Views/Advanced%20Search%20Modal)
[Log View](https://z-edit.github.io/#/docs?t=Views/Edit%20Veiw/Log%20View)

Also, seemingly every link (I haven't tested them all) break the history stack such that going backwards doesn't do anything unless you go back to a previous website.

**Comment by matortheeternal** [comment]
It looks to me like the history stack is getting "broken" by the page creating a new "history entry" upon navigation (likely due to it setting the URL when unnecessary).  I'm surprised browsers don't handle that better.

The Advanced Search Modal page doesn't exist yet, so I'll remove that link temporarily.  Log View link is broken because of a typo, will fix that.  Changes will be deployed to the site but internal application documentation won't be updated until the next release.

**Comment by matortheeternal** [comment]
Moved browser history broken to [separate issue in the website repo](https://github.com/z-edit/z-edit.github.io/issues/1) because it doesn't affect the zEdit application.  The links being broken has been resolved.
