### ISSUE TITLE
Cant use Zedit for Skyrim LE, MO cant manage x64 programs..

### ISSUE THREAD

**Issue by Gargolon** [matortheeternal/zedit#93]
Cant use Zedit for Skyrim LE, MO cant manage x64 programs..

**Comment by matortheeternal** [comment]
Use MO2.

**Comment by ThisIsPatrick** [comment]
MO2 still doesn't offer BSA parsing or archive management (last I knew of.)
These are important features to me that I refuse to do without.

**Comment by matortheeternal** [comment]
The archive management feature was considered poor practice by Tannin, and thus wasn't built into MO2.  I personally did like the feature myself, but it's not too hard to work without it.  I don't know if MO2 will ever support archive management like MO did, so I wouldn't hold out hope for it.

zEdit is a 64-bit application and cannot be compiled stably for x86 due to issues with chromium memory management when dynamically linked third party libraries allocate large amounts of memory.  I *could* provide x86 versions, but they will be unstable and unreliable to the point that many users will consistently crash when loading plugin files.  This is not acceptable to me so I will not be making an x86 release unless this issue disappears due to the work of other developers.
